name: Full Stack Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - test
          - qa
          - staging
          - production
      deploy_infrastructure:
        description: 'Deploy infrastructure changes'
        required: false
        default: true
        type: boolean
      deploy_application:
        description: 'Deploy application changes'
        required: false
        default: true
        type: boolean
      infrastructure_action:
        description: 'Infrastructure action (only if deploy_infrastructure is true)'
        required: false
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - destroy
      skip_tests:
        description: 'Skip application tests'
        required: false
        default: false
        type: boolean
      auto_approve:
        description: 'Auto approve deployments'
        required: false
        default: false
        type: boolean

jobs:
  deploy_infrastructure:
    name: Deploy Infrastructure
    if: ${{ inputs.deploy_infrastructure }}
    uses: ./.github/workflows/infra-pipeline.yml
    with:
      environment: ${{ inputs.environment }}
      action: ${{ inputs.infrastructure_action }}
      auto_approve: ${{ inputs.auto_approve }}
    secrets: inherit

  deploy_application:
    name: Deploy Application
    if: ${{ inputs.deploy_application }}
    needs: deploy_infrastructure
    condition: always() && (needs.deploy_infrastructure.result == 'success' || needs.deploy_infrastructure.result == 'skipped')
    uses: ./.github/workflows/app-pipeline.yml
    with:
      environment: ${{ inputs.environment }}
      skip_tests: ${{ inputs.skip_tests }}
    secrets: inherit

  notify_completion:
    name: Notify Deployment Completion
    runs-on: ubuntu-latest
    needs: [deploy_infrastructure, deploy_application]
    if: always()
    
    steps:
    - name: Send completion notification
      run: |
        echo "🚀 Full Stack Deployment Summary:"
        echo "Environment: ${{ inputs.environment }}"
        echo "Infrastructure: ${{ inputs.deploy_infrastructure && needs.deploy_infrastructure.result || 'skipped' }}"
        echo "Application: ${{ inputs.deploy_application && needs.deploy_application.result || 'skipped' }}"
        
        if [[ "${{ needs.deploy_infrastructure.result }}" == "success" ]] || [[ "${{ needs.deploy_application.result }}" == "success" ]]; then
          echo "✅ Deployment completed successfully!"
        else
          echo "❌ Deployment encountered issues!"
        fi